// Script that ensures that the inputs generated by the generator
// only contains letters and spaces.

#include<bits/stdc++.h>
using namespace std;

int main() {
  ios::sync_with_stdio(false);

  while(true) {
    string s;
    std::getline(std::cin, s);
    if (not cin) break;

    for(int i = 0; i < s.size(); i++) {
      if(isalpha(s[i])) cout << s[i];
      else if(s[i] == ' ') cout << s[i];
      else if (s[i]  == '\n') cout << s[i];
    }
    cout << endl;
  }

  return 0;
}
